### ISSUE TITLE
can't get -container of quill element in on.text-change when code is optimized

### ISSUE THREAD

**Issue by willspecht** [benhowell/reagent-quill#1]
I'm facing a weird issue where minimizing this code with google closure creates a weird issue.  

I'm getting an `Uncaught TypeError: Cannot read property 'firstChild' of undefined` error, but only when packaging with`lein cljsbuild once min`, when running in dev mode locally, it's working fine.  

https://github.com/benhowell/reagent-quill/blob/master/quill.cljs#L72 is throwing the error, it seems that `#(.. @this -container -firstChild -innerHTML)` can't find container in this.  even tho it seems to be there with any logging I am doing

**Comment by benhowell** [comment]
The error you're getting will be due to closure advanced compilation munging the raw javascript function (js/Quill.) here: https://github.com/benhowell/reagent-quill/blob/master/quill.cljs#L64

You'll either need to add an externs file to your clojurescript build to tell the closure compiler to not munge that function or rewrite the code starting at https://github.com/benhowell/reagent-quill/blob/master/quill.cljs#L64 inside a function marked with the `^:export` keyword to tell the compiler not to munge it.

Read more about externs here:
http://www.spacjer.com/blog/2014/09/12/clojurescript-javascript-interop/
https://clojurescript.org/reference/dependencies

**Comment by willspecht** [comment]
@benhowell I added a PR that fixes the issue pretty cleanly.  using `aget` instead of `.-` calls by name instead of reference and prevents closure compiler from breaking during optimization.  Thought I would have to use https://github.com/binaryage/cljs-oops, but aget seems to work for me at least.

**Comment by benhowell** [comment]
Just to confirm that my initial analysis was wrong. @willspecht fixed this issue in https://github.com/benhowell/reagent-quill/pull/2
